### ISSUE TITLE
Error with Pie chart and Multibar Graph Panel on dashboard

### ISSUE THREAD

**Issue by deepminimal** [CorpGlory/grafana-multibar-graph-panel#7]
Hello again!
I have issue with Multibar Graph Panel. 
1) Add Multibar Graph Panel
![image](https://user-images.githubusercontent.com/18044597/38139400-ec2d4db6-3437-11e8-950f-c71f7d985245.png)

2) Add Pie chart
![image](https://user-images.githubusercontent.com/18044597/38139414-fd7ffd0c-3437-11e8-81f3-4c7b06df35b2.png)

1.1) Delete Multibar Graph Panel
![image](https://user-images.githubusercontent.com/18044597/38139529-767ef9ce-3438-11e8-8e37-aaf3b3f6bf66.png)

node -v
v9.8.0

npm -v
5.8.0

grafana-cli -v
Grafana cli version 4.6.3

Centos 7.

**Comment by rozetko** [comment]
Hi @deepminimal! 

Have you tested it with default Grafana's Graph plugin? 

I haven't ever used PieChart plugin. So can you please explain what is expected behaviour?

**Comment by deepminimal** [comment]
https://grafana.com/plugins/grafana-piechart-panel/installation   Pie Chart is a plugin from Grafana Labs.

I want to use Pie chart and Multibar Graph Panel in one dashboard.

With standart Graph panel everything is ok. 
![image](https://user-images.githubusercontent.com/18044597/38140399-32247ad4-343c-11e8-81e7-1c341e734981.png)


But when i add Multibar Graph Panel, a Pie Chart panel broken like this:
![image](https://user-images.githubusercontent.com/18044597/38140465-736c10e2-343c-11e8-97ed-6759f2e43fa7.png)

**Comment by rozetko** [comment]
@deepminimal OK, i see. Need to do some research to fix this bug. Will keep you informed.

BTW, thanks for detailed description with screenshots!

**Comment by nsayedqt** [comment]
Any update on this? I am seeing similar results. when I add the multi bar graph, all my pie charts in the dashboard go blank.

**Comment by jonyrock** [comment]
@rozetko can I ask you to explore it a bit. Is it connected with https://github.com/CorpGlory/grafana-graph-panel/issues/6 ?

**Comment by rozetko** [comment]
@jonyrock ok, I'll look into this

**Comment by sankerust** [comment]
@jonyrock Seems like current issue is not connected to https://github.com/CorpGlory/grafana-graph-panel/issues/6.
However same bug is here:
  https://github.com/CorpGlory/grafana-graph-panel/issues/7

Will keep looking into it.

**Comment by rozetko** [comment]
Hey, @deepminimal @nsayedqt
Here is an update on this issue. I managed to fix it for initial [grafana-graph-panel](https://github.com/CorpGlory/grafana-graph-panel) plugin.
This PR fixes it: https://github.com/CorpGlory/grafana-graph-panel/pull/8
But, unfortunately, I came up with some problems with integrating it into this repo
If someone could do it - PRs would be appreciated

**Comment by rozetko** [comment]
Here is the solution:
https://github.com/hastic/hastic-grafana-graph-panel/pull/53/files

**Comment by nsayedqt** [comment]
Any update on integrating the above solution into this repo? I am still seeing the issue. Would really appreciate if the solution can be merged here. Thanks

**Comment by rozetko** [comment]
@nsayedqt unfortunately, there is no time to fix it in this repo
If someone can apply solution above - PR would be appreciated

**Comment by rozetko** [comment]
@nsayedqt @deepminimal bug is fixed via this PR https://github.com/CorpGlory/grafana-multibar-graph-panel/pull/15
But fix created another bug (https://github.com/CorpGlory/grafana-multibar-graph-panel/issues/16), working on it
![image](https://user-images.githubusercontent.com/1989898/46546056-bded5300-c8d0-11e8-8ba1-d96b4ae52688.png)

**Comment by rozetko** [comment]
@nsayedqt @deepminimal #16 is fixed also

**Comment by davidfa94** [comment]
Hello everyone,

I have **Grafana v6.5.3 (24e5e75)** and the bug still exists for me.

The behaviour is the same as @deepminimal explained, but actually a little bit worse: once I add a Multibar Graph Panel, my Pie Chart gets screwed up forever. Even removing the Multibar panel doesn't fix it.
